databases:
  - name: registro-nis2-db
    plan: free
    databaseName: registro_nis2

services:
  - type: web
    name: registro-nis2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: registro-nis2-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11
